#!/usr/bin/env bash
# Regenerates Sources/VoxKit/ReferenceWordFrequencies.swift, the general-English
# word-frequency table `vox vocab seed` scores corpora against.
#
# Source: hackerb9/gwordlist `frequency-alpha-alldicts.txt`, a per-word total
# over the Google Books Ngram corpus (v3, 2020) restricted to dictionary words,
# released under CC BY 3.0 (the license Google grants for the Ngram data).
# Only the top $WORDS entries are embedded; counts are stored in thousands.
set -euo pipefail

WORDS="${WORDS:-30000}"
SOURCE_URL="https://raw.githubusercontent.com/hackerb9/gwordlist/master/frequency-alpha-alldicts.txt"
OUT="$(dirname "$0")/../Sources/VoxKit/ReferenceWordFrequencies.swift"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
curl -fsSL "$SOURCE_URL" -o "$tmp"

# Total corpus size, recovered from the first row's count and percentage.
total="$(awk 'NR == 2 { gsub(",", "", $3); sub("%", "", $4); printf "%.0f", $3 / ($4 / 100) }' "$tmp")"

{
  cat <<EOF
// Generated by scripts/generate-reference-frequencies.sh — do not edit by hand.
//
// General-English word frequencies used by \`CorpusVocabularyExtractor\` as the
// baseline a corpus is compared against. Derived from hackerb9/gwordlist
// (frequency-alpha-alldicts.txt): Google Books Ngram v3 (2020) 1-gram totals
// restricted to dictionary words, top $WORDS entries, counts in thousands.
// Data license: Creative Commons Attribution 3.0 (CC BY 3.0), as granted by
// Google for the Ngram datasets and passed through by hackerb9.

enum ReferenceWordFrequencies {
    /// Tokens in the full reference corpus (not just the embedded subset).
    static let totalTokens: Double = $total

    /// One \`word count\` pair per line, most frequent first; counts in thousands.
    static let table = """
EOF
  awk -v n="$WORDS" 'NR > 1 && NR <= n + 1 { gsub(",", "", $3); printf "%s %d\n", tolower($2), $3 / 1000 }' "$tmp" \
    | awk '!seen[$1]++'
  cat <<'EOF'
"""
}
EOF
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
